apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmxjh9662-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmxjh9662-tenant-component
    app.kubernetes.io/part-of: loadmxjh9662-tenant-app
  name: loadmxjh9662-tenant-component
  namespace: loadmxjh9662-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmxjh9662-tenant-component
    weight: null
status: {}
